"""Add pdf_filename to Book table

Revision ID: a821f78a72c6
Revises: e4ea49bb20b6
Create Date: 2026-03-25 20:53:40.919156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a821f78a72c6'
down_revision = 'e4ea49bb20b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('pdf_filename')

    # ### end Alembic commands ###
